//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string MaSach { get; set; }
        public string Anh { get; set; }
        public string TenSach { get; set; }
        public string TheLoai { get; set; }
        public string TacGia { get; set; }
        public int DonGia { get; set; }
        public string TonDau { get; set; }
        public string TongNhap { get; set; }
        public string TongBan { get; set; }
        public string PhatSinh { get; set; }
        public string ViTri { get; set; }
        public int TonCuoi { get; set; }
    }
}
